services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visionhub-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - visionhub-network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: visionhub-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - visionhub-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: visionhub-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: visionhub
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: visionhub
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - visionhub-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: visionhub-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - visionhub-network
    depends_on:
      - db

volumes:
  mysql-data:

networks:
  visionhub-network:
    driver: bridge